import type { QaScenario } from '../types.ts';

export const golden100Scenarios:QaScenario[]=[
  {id:'G100-01-CONSTRUCTION',family:'COMMERCIAL',title:'Construcción: necesidad, batería, presupuesto y compra',turns:[
    {message:'Trabajo en construcción y el cel se me cae seguido, necesito uno resistente.',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE',expectedState:{problem:'caidas_frecuentes'}}},
    {message:'y q la bateria dure todo el dia porque casi no cargo',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE'}},
    {message:'maximo 1500 soles',expected:{intent:'BUDGET_CONSTRAINT',budget:1500},oracleSpec:{domain:'MEMORY',intentClass:'BUDGET_CONSTRAINT',expectedState:{budget:1500}}},
    {message:'cual me recomiendas entonces?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND'}},
    {message:'ya ese quiero, como compro?',expected:{intent:'PURCHASE'},oracleSpec:{domain:'MEMORY',intentClass:'PURCHASE',requiresHandoff:false,expectedNba:'COLLECT_RESERVATION_DATA',expectedState:{purchaseSignal:true,reservationStage:'NEED_DOCUMENT'}}},
  ]},
  {id:'G100-02-DELIVERY',family:'COMMERCIAL',title:'Delivery: caídas, GPS, autonomía y decisión',turns:[
    {message:'hago delivery todo el dia, quiero algo q aguante golpes',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE'}},
    {message:'tambien uso gps siempre y datos todo el tiempo',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE'}},
    {message:'hay algo por menos de 1000?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND_WITHIN_BUDGET',expectedState:{budget:1000}}},
    {message:'el recomendado tiene buena bateria?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',sections:['BATERIA'],expectedReferenceBehavior:'RECOMMENDED'}},
    {message:'cuanto esta ese',oracleSpec:{domain:'SQL',intentClass:'PRICE',expectedReferenceBehavior:'RECOMMENDED'}},
  ]},
  {id:'G100-03-PERSONAL-BUDGET',family:'COMMERCIAL',title:'Uso diario con presupuesto estricto',turns:[
    {message:'quiero uno resistente pero para uso normal y trabajo',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE'}},
    {message:'mi tope es 900',expected:{budget:900},oracleSpec:{domain:'MEMORY',intentClass:'BUDGET_CONSTRAINT',expectedState:{budget:900}}},
    {message:'q modelo entra?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND_WITHIN_BUDGET'}},
    {message:'y camara q tal?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',sections:['CAMARA'],expectedReferenceBehavior:'RECOMMENDED'}},
    {message:'si esta disponible me interesa',oracleSpec:{domain:'SQL',intentClass:'STOCK',expectedReferenceBehavior:'RECOMMENDED'}},
  ]},
  {id:'G100-04-SIMPLE-USE',family:'COMMERCIAL',title:'Cliente quiere equipo simple sin sobreventa',turns:[
    {message:'no necesito lo mas caro, solo llamadas whatsapp y que sea resistente',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE'}},
    {message:'que me recomiendas sin irme a algo exagerado?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND'}},
    {message:'tiene buena pantalla?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',sections:['PANTALLA'],expectedReferenceBehavior:'RECOMMENDED'}},
    {message:'y memoria?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',sections:['MEMORIA'],expectedReferenceBehavior:'RECOMMENDED'}},
    {message:'ok cuanto cuesta',oracleSpec:{domain:'SQL',intentClass:'PRICE',expectedReferenceBehavior:'RECOMMENDED'}},
  ]},
  {id:'G100-05-CAMERA',family:'COMMERCIAL',title:'Cámara para trabajo y redes',turns:[
    {message:'necesito tomar fotos de trabajos y subirlas a redes, pero quiero algo resistente',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE'}},
    {message:'entre los que tienen cual conviene por camara?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND'}},
    {message:'ese graba buen video?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',sections:['CAMARA'],expectedReferenceBehavior:'RECOMMENDED'}},
    {message:'tiene espacio suficiente?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',sections:['MEMORIA'],expectedReferenceBehavior:'RECOMMENDED'}},
    {message:'mandame fotos del equipo',oracleSpec:{domain:'SQL',intentClass:'IMAGE',expectedReferenceBehavior:'RECOMMENDED'}},
  ]},
  {id:'G100-06-COMPARE-X13-22',family:'COMPARISON',title:'Comparación sostenida X13 vs Armor 22',turns:[
    {message:'estoy entre Armor X13 y Armor 22, comparalos',expected:{intent:'COMPARE'},oracleSpec:{domain:'PRODUCT_RAG',intentClass:'COMPARE',products:['Armor X13','Armor 22'],sections:['RESISTENCIA','BATERIA','RENDIMIENTO','CAMARA']}},
    {message:'cual tiene mejor bateria?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'COMPARE',products:['Armor X13','Armor 22'],sections:['BATERIA'],expectedReferenceBehavior:'COMPARISON_PAIR'}},
    {message:'y en camara?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'COMPARE',products:['Armor X13','Armor 22'],sections:['CAMARA'],expectedReferenceBehavior:'COMPARISON_PAIR'}},
    {message:'precio del X13',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor X13'}},
    {message:'y el otro?',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor 22',expectedReferenceBehavior:'OTHER_IN_PAIR'}},
  ]},
  {id:'G100-07-REFERENCES',family:'REFERENCE',title:'Referentes ese, otro y selección explícita',turns:[
    {message:'cuanto cuesta el Armor X13?',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor X13'}},
    {message:'tambien estoy viendo el Armor 22',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedReferenceBehavior:'MENTION_NO_SWITCH'}},
    {message:'q diferencia hay entre los dos?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'COMPARE',product:'Armor X13',sections:['RESISTENCIA','BATERIA','RENDIMIENTO','CAMARA'],expectedReferenceBehavior:'COMPARISON_PAIR'}},
    {message:'prefiero el Armor 22',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedReferenceBehavior:'EXPLICIT_SWITCH',expectedState:{activeProduct:'Armor 22'}}},
    {message:'ese tiene stock?',oracleSpec:{domain:'SQL',intentClass:'STOCK',product:'Armor 22',expectedReferenceBehavior:'SELECTED'}},
  ]},
  {id:'G100-08-UNKNOWN',family:'TRUTH',title:'Producto inexistente y recuperación con alternativa',turns:[
    {message:'tienen el Armor 30?',oracleSpec:{domain:'SQL',intentClass:'PRODUCT_INFO',product:'Armor 30',expectedNba:'OFFER_ALTERNATIVES'}},
    {message:'mejor dime del Armor X13',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedState:{activeProduct:'Armor X13'}}},
    {message:'aguanta caidas?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor X13',sections:['RESISTENCIA']}},
    {message:'cuanto cuesta ese?',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor X13'}},
    {message:'ya ese quiero',oracleSpec:{domain:'MEMORY',intentClass:'PURCHASE',requiresHandoff:false,expectedNba:'COLLECT_RESERVATION_DATA',expectedState:{purchaseSignal:true,reservationStage:'NEED_DOCUMENT'}}},
  ]},
  {id:'G100-09-X13-SPECS',family:'TRUTH',title:'Preguntas técnicas variadas Armor X13',turns:[
    {message:'el Armor X13 tiene NFC?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor X13',sections:['CONECTIVIDAD','FUNCIONES']}},
    {message:'es 5g?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor X13',sections:['REDES','CONECTIVIDAD']}},
    {message:'cuanta ram tiene?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor X13',sections:['MEMORIA']}},
    {message:'que bateria trae?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor X13',sections:['BATERIA']}},
    {message:'aguanta agua y polvo?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor X13',sections:['RESISTENCIA']}},
  ]},
  {id:'G100-10-ARMOR22-SPECS',family:'TRUTH',title:'Preguntas técnicas variadas Armor 22',turns:[
    {message:'dame info del Armor 22',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'PRODUCT_INFO',product:'Armor 22',sections:['PANTALLA','RENDIMIENTO','MEMORIA','CAMARA','BATERIA','RESISTENCIA']}},
    {message:'q procesador tiene?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor 22',sections:['RENDIMIENTO']}},
    {message:'tiene huella?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor 22',sections:['SEGURIDAD','SENSORES']}},
    {message:'acepta dual sim?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor 22',sections:['SIM','REDES']}},
    {message:'q peso tiene?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor 22',sections:['FISICO']}},
  ]},
  {id:'G100-11-SHIPPING',family:'POLICY',title:'Envíos Lima y provincias',turns:[
    {message:'hacen envios?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'envios',subcategory:'disponibilidad'}}},
    {message:'cuanto demora en lima?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'envios',subcategory:'plazo_variable'}}},
    {message:'y a arequipa?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'envios',subcategory:'plazo_variable'}}},
    {message:'el envio es gratis?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'envios',subcategory:'envio_gratuito'}}},
    {message:'puedo recoger en tienda mejor?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'entrega',subcategory:'recojo_tienda'}}},
  ]},
  {id:'G100-12-PAYMENTS',family:'POLICY',title:'Pagos, contraentrega y confirmación',turns:[
    {message:'puedo pagar con yape?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'pagos',subcategory:'medios_pago'}}},
    {message:'aceptan tarjeta?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'pagos',subcategory:'medios_pago'}}},
    {message:'trabajan contraentrega?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'pagos',subcategory:'contraentrega'}}},
    {message:'como validan mi pago?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'pagos',subcategory:'validacion_pago'}}},
    {message:'como se confirma el pedido?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'pagos',subcategory:'confirmacion_pedido'}}},
  ]},
  {id:'G100-13-WARRANTY',family:'INSTITUTIONAL',title:'Garantía y postventa',turns:[
    {message:'que garantia dan?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'WARRANTY',institutionalTopic:{category:'postventa',subcategory:'garantia_general'}}},
    {message:'si falla me lo cambian?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'WARRANTY',institutionalTopic:{category:'garantia',subcategory:'evaluacion_y_resultado'}}},
    {message:'como es el proceso de postventa?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'postventa',subcategory:'postventa_procedimiento'}}},
    {message:'puedo devolverlo?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'postventa',subcategory:'cambios_devoluciones'}}},
    {message:'y cuanto demora el reembolso?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'postventa',subcategory:'reembolsos'}}},
  ]},
  {id:'G100-14-LOCATION-PRIVACY',family:'POLICY',title:'Ubicación, horario y privacidad',turns:[
    {message:'donde queda su tienda?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'ubicacion',subcategory:'direccion'}}},
    {message:'hasta q hora atienden?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'ubicacion',subcategory:'horario'}}},
    {message:'q hacen con mis datos personales?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'privacidad',subcategory:'privacidad_general'}}},
    {message:'usan cookies?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'privacidad',subcategory:'privacidad_cookies'}}},
    {message:'puedo pedir que borren mis datos?',oracleSpec:{domain:'INSTITUTIONAL_RAG',intentClass:'POLICY',institutionalTopic:{category:'privacidad',subcategory:'privacidad_derechos'}}},
  ]},
  {id:'G100-15-PRICE-OBJECTION',family:'COMMERCIAL',title:'Objeción de precio sin repetir producto',turns:[
    {message:'me interesa el Armor 22',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedState:{activeProduct:'Armor 22'}}},
    {message:'cuanto cuesta?',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor 22'}},
    {message:'esta caro para mi',oracleSpec:{domain:'MEMORY',intentClass:'HANDLE_PRICE_OBJECTION'}},
    {message:'hay uno mas barato pero resistente?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND'}},
    {message:'cuanto sale esa alternativa?',oracleSpec:{domain:'SQL',intentClass:'PRICE',expectedReferenceBehavior:'RECOMMENDED'}},
  ]},
  {id:'G100-16-ALTERNATIVES',family:'COMMERCIAL',title:'Alternativas por necesidad cambiante',turns:[
    {message:'quiero el mas resistente q tengan',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND'}},
    {message:'pero no quiero gastar tanto',oracleSpec:{domain:'MEMORY',intentClass:'HANDLE_PRICE_OBJECTION'}},
    {message:'tengo 1000 maximo',oracleSpec:{domain:'MEMORY',intentClass:'BUDGET_CONSTRAINT',expectedState:{budget:1000}}},
    {message:'cual queda como mejor opcion?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND_WITHIN_BUDGET'}},
    {message:'ese tiene stock?',oracleSpec:{domain:'SQL',intentClass:'STOCK',expectedReferenceBehavior:'RECOMMENDED'}},
  ]},
  {id:'G100-17-PURCHASE',family:'CLOSING',title:'Compra personal progresa a asesor',turns:[
    {message:'quiero ver el Armor X13',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedState:{activeProduct:'Armor X13'}}},
    {message:'precio?',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor X13'}},
    {message:'hay stock?',oracleSpec:{domain:'SQL',intentClass:'STOCK',product:'Armor X13'}},
    {message:'si esta disponible me interesa',oracleSpec:{domain:'SQL',intentClass:'STOCK',product:'Armor X13',expectedState:{interestSignal:true,purchaseSignal:false}}},
    {message:'ya me decidi por ese',oracleSpec:{domain:'MEMORY',intentClass:'PURCHASE',expectedReferenceBehavior:'SELECTED',requiresHandoff:false,expectedNba:'COLLECT_RESERVATION_DATA',expectedState:{purchaseSignal:true,reservationStage:'NEED_DOCUMENT'}}},
  ]},
  {id:'G100-18-BUSINESS-12',family:'INSTITUTIONAL',title:'Empresa compra 12 equipos para técnicos',turns:[
    {message:'somos empresa y necesitamos 12 celulares para tecnicos de campo',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE',expectedState:{quantity:12}}},
    {message:'resistentes y con buena bateria, necesitamos factura',oracleSpec:{domain:'MEMORY',intentClass:'EVALUATE_USE',expectedState:{invoiceRequired:true}}},
    {message:'q modelos recomiendan?',oracleSpec:{domain:'SQL',intentClass:'RECOMMEND'}},
    {message:'tienen stock para las 12?',oracleSpec:{domain:'SQL',intentClass:'STOCK',expectedReferenceBehavior:'RECOMMENDED'}},
    {message:'quiero q un asesor siga con la compra',oracleSpec:{domain:'HANDOFF',intentClass:'HUMAN',requiresHandoff:true,expectedNba:'ASSISTED_HANDOFF'}},
  ]},
  {id:'G100-19-CHANGE-PRODUCT',family:'REFERENCE',title:'Persona evalúa otro equipo sin cambio silencioso',turns:[
    {message:'quiero ver el Armor X13',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedState:{activeProduct:'Armor X13'}}},
    {message:'cuanto cuesta?',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor X13'}},
    {message:'tambien estoy viendo el Armor 22',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedReferenceBehavior:'MENTION_NO_SWITCH',expectedState:{activeProduct:'Armor X13'}}},
    {message:'q diferencia hay entre los dos?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'COMPARE',products:['Armor X13','Armor 22'],sections:['RESISTENCIA','BATERIA','RENDIMIENTO','CAMARA'],expectedReferenceBehavior:'COMPARISON_PAIR'}},
    {message:'prefiero el Armor 22',oracleSpec:{domain:'MEMORY',intentClass:'PRODUCT_INFO',expectedReferenceBehavior:'EXPLICIT_SWITCH',expectedState:{activeProduct:'Armor 22'}}},
  ]},
  {id:'G100-20-REAL-WRITING',family:'RELIABILITY',title:'Mensajes cortos, typos y referencias naturales',turns:[
    {message:'armro x13 cuanto ta',oracleSpec:{domain:'SQL',intentClass:'PRICE',product:'Armor X13'}},
    {message:'y stk?',oracleSpec:{domain:'SQL',intentClass:'STOCK',product:'Armor X13'}},
    {message:'foto ps',oracleSpec:{domain:'SQL',intentClass:'IMAGE',product:'Armor X13'}},
    {message:'y el 22 es mejor bateria?',oracleSpec:{domain:'PRODUCT_RAG',intentClass:'CAPABILITY',product:'Armor 22',sections:['BATERIA'],expectedReferenceBehavior:'MENTION_NO_SWITCH'}},
    {message:'ya el 22 quiero',oracleSpec:{domain:'MEMORY',intentClass:'PURCHASE',product:'Armor 22',requiresHandoff:false,expectedNba:'COLLECT_RESERVATION_DATA',expectedState:{purchaseSignal:true,reservationStage:'NEED_DOCUMENT'}}},
  ]},
];
