import type { QaScenario } from '../types.ts';

export const journeyScenarios: QaScenario[] = [
  {
    id: 'JOURNEY-WORK-CONSTRUCTION',
    family: 'COMMERCIAL',
    title: 'Trabajador de construcción: necesidad, presupuesto, comparación, objeción y cierre',
    turns: [
      { message: 'Hola, trabajo en construcción y se me caen seguido los celulares. Necesito algo resistente.' },
      { message: 'También necesito que la batería me aguante toda la jornada porque casi no tengo dónde cargarlo.' },
      { message: 'Tengo máximo S/ 1500.', expected: { intent: 'BUDGET_CONSTRAINT', budget: 1500 } },
      { message: '¿Cuál me recomiendas dentro de ese presupuesto?', expected: { intent: 'RECOMMEND_WITHIN_BUDGET', budget: 1500 } },
      { message: '¿Qué diferencia hay entre el recomendado y el Armor X13?', expected: { intent: 'COMPARE' } },
      { message: 'Prefiero la batería del Armor X13, pero todavía no quiero cambiar de equipo.', expected: { intent: 'CAPABILITY', explicitSwitch: false } },
      { message: '¿Cuánto cuesta el que me recomendaste?', expected: { intent: 'PRICE', budget: 1500 } },
      { message: '¿Tienen stock del recomendado?', expected: { intent: 'STOCK', budget: 1500 } },
      { message: 'Está un poco caro. ¿Hay una opción que siga siendo resistente?', expected: { intent: 'HANDLE_PRICE_OBJECTION', budget: 1500 } },
      { message: 'Me quedo con ese, quiero comprarlo.', expected: { intent: 'PURCHASE' } },
    ],
  },
  {
    id: 'JOURNEY-COMPARE-X13-22',
    family: 'COMPARISON',
    title: 'Comparación sostenida Armor X13 vs Armor 22 con referencias y cambio explícito',
    turns: [
      { message: 'Estoy entre el Armor X13 y el Armor 22. Compáralos para trabajo.', expected: { intent: 'COMPARE' } },
      { message: '¿Cuál de los dos tiene mejor batería?', expected: { intent: 'CAPABILITY' } },
      { message: '¿Y en cámara cuál conviene más?', expected: { intent: 'CAPABILITY' } },
      { message: '¿Cuánto cuesta el Armor X13?', expected: { intent: 'PRICE', queryTarget: 'Armor X13' } },
      { message: '¿Y el otro cuánto cuesta?', expected: { intent: 'PRICE' } },
      { message: 'En otra tienda vi uno más barato. ¿Eso cambia tu recomendación?', expected: { explicitSwitch: false } },
      { message: 'Prefiero el Armor 22.', expected: { activeProduct: 'Armor 22', explicitSwitch: true } },
      { message: '¿Ese tiene stock?', expected: { intent: 'STOCK', activeProduct: 'Armor 22' } },
      { message: 'Entonces me quedo con ese.', expected: { intent: 'PURCHASE', activeProduct: 'Armor 22' } },
    ],
  },
  {
    id: 'JOURNEY-PERSONAL-BUDGET',
    family: 'COMMERCIAL',
    title: 'Compra personal: uso diario, presupuesto, recomendación, objeción y decisión',
    turns: [
      { message: 'Busco un celular resistente para uso diario y trabajo, pero no necesito algo industrial extremo.' },
      { message: 'Mi presupuesto es máximo S/ 1000.', expected: { intent: 'BUDGET_CONSTRAINT', budget: 1000 } },
      { message: '¿Qué modelo entra en ese presupuesto?', expected: { intent: 'RECOMMEND_WITHIN_BUDGET', budget: 1000 } },
      { message: '¿Tiene buena batería y cámara para el día a día?', expected: { intent: 'CAPABILITY', budget: 1000 } },
      { message: '¿Cuánto cuesta exactamente el recomendado?', expected: { intent: 'PRICE', budget: 1000 } },
      { message: 'Se me hace caro para lo que pensaba gastar.', expected: { intent: 'HANDLE_PRICE_OBJECTION', budget: 1000 } },
      { message: '¿Hay otra opción más económica sin perder resistencia?' },
      { message: 'Ya, me quedo con el que me recomiendas.', expected: { intent: 'PURCHASE', budget: 1000 } },
    ],
  },
  {
    id: 'JOURNEY-INSTITUTIONAL-TEAM',
    family: 'INSTITUTIONAL',
    title: 'Empresa: compra para equipo, factura, volumen, stock, garantía y derivación comercial',
    turns: [
      { message: 'Somos una empresa y necesitamos celulares para 12 técnicos que trabajan en campo.' },
      { message: 'Necesitamos equipos resistentes, buena batería y factura para la empresa.' },
      { message: '¿Qué modelos nos recomendarías para ese uso?' },
      { message: 'Compárame el Armor X13 con el Armor 22 para ese escenario.', expected: { intent: 'COMPARE' } },
      { message: '¿Cuánto cuesta el Armor 22?', expected: { intent: 'PRICE', queryTarget: 'Armor 22' } },
      { message: '¿Tienen stock suficiente para 12 unidades?', expected: { intent: 'STOCK', activeProduct: 'Armor 22' } },
      { message: '¿Qué garantía tendríamos por los equipos?', expected: { intent: 'WARRANTY', activeProduct: 'Armor 22' } },
      { message: '¿Pueden cotizarnos las 12 unidades con envío a Lima?' },
      { message: 'Quiero avanzar con la compra y que un asesor continúe con nosotros.', expected: { intent: 'PURCHASE', activeProduct: 'Armor 22' } },
    ],
  },
  {
    id: 'JOURNEY-POLICIES-BEFORE-BUY',
    family: 'POLICY',
    title: 'Cliente consulta políticas antes de comprar sin permitir invenciones',
    turns: [
      { message: 'Hola, antes de comprar quisiera aclarar unas cosas.' },
      { message: '¿Tienen tienda física o puedo recoger el equipo personalmente?' },
      { message: '¿Cuánto demora el envío dentro de Lima?' },
      { message: '¿Y si lo envío a provincia?' },
      { message: '¿Trabajan contraentrega?' },
      { message: '¿Qué garantía dan?' , expected: { intent: 'WARRANTY' } },
      { message: '¿Qué formas de pago aceptan?' },
      { message: 'Perfecto, ahora sí quiero ver el Armor X13.', expected: { activeProduct: 'Armor X13' } },
      { message: '¿Cuánto cuesta?', expected: { intent: 'PRICE', queryTarget: 'Armor X13', activeProduct: 'Armor X13' } },
    ],
  },
  {
    id: 'JOURNEY-REFERENCE-STRESS',
    family: 'REFERENCE',
    title: 'Estrés de memoria y referencias durante una conversación larga',
    turns: [
      { message: '¿Cuánto cuesta el Armor X13?', expected: { intent: 'PRICE', activeProduct: 'Armor X13', queryTarget: 'Armor X13' } },
      { message: '¿Y tienen stock?', expected: { intent: 'STOCK', activeProduct: 'Armor X13', queryTarget: 'Armor X13' } },
      { message: 'También estoy viendo el Armor 22.', expected: { activeProduct: 'Armor X13', queryTarget: 'Armor 22', explicitSwitch: false } },
      { message: '¿Qué diferencia hay entre los dos?', expected: { intent: 'COMPARE' } },
      { message: 'Prefiero la batería del Armor 22.', expected: { activeProduct: 'Armor X13', explicitSwitch: false } },
      { message: '¿Y cuánto cuesta el otro?', expected: { intent: 'PRICE' } },
      { message: 'Prefiero el Armor 22.', expected: { activeProduct: 'Armor 22', explicitSwitch: true } },
      { message: 'En otra tienda me ofrecieron un descuento.', expected: { activeProduct: 'Armor 22', explicitSwitch: false } },
      { message: '¿El otro tiene stock?', expected: { intent: 'STOCK' } },
      { message: 'Ya entendí. Me quedo con ese.', expected: { intent: 'PURCHASE' } },
    ],
  },
  {
    id: 'JOURNEY-UNKNOWN-SAFETY',
    family: 'TRUTH',
    title: 'Producto no reconocido: mantener UNKNOWN y recuperar conversación sin inventar',
    turns: [
      { message: 'Hola, dame información del Armor 30.' },
      { message: '¿Cuánto cuesta?' },
      { message: '¿Tienen stock?' },
      { message: '¿Tiene 5G, NFC y buena batería?', expected: { intent: 'CAPABILITY' } },
      { message: 'Mejor dime el precio del Armor X13.', expected: { intent: 'PRICE', queryTarget: 'Armor X13', activeProduct: 'Armor X13' } },
      { message: '¿Y tienen stock de ese?', expected: { intent: 'STOCK', queryTarget: 'Armor X13', activeProduct: 'Armor X13' } },
    ],
  },
];
