import test from 'node:test';
import assert from 'node:assert/strict';
import { buildProductFactStores } from '../../src/conversation/commercial/FullRagFactKernel.ts';
import { buildFullRagAnswer } from '../../src/conversation/commercial/FullRagAnswerKernel.ts';
import { FullRagLlmProvider } from '../../src/conversation/commercial/FullRagLlmProvider.ts';

const rows:any[]=[
  {domain:'PRODUCT',productId:'P-22',section:'MEMORIA',source:'TEST',text:'Producto: Armor 22\n- RAM física: 8 GB.\n- RAM virtual máxima: 8 GB.\n- Almacenamiento interno: 256 GB.\n- microSD máxima: 512 GB.'},
  {domain:'PRODUCT',productId:'P-22',section:'BATERIA',source:'TEST',text:'Producto: Armor 22\n- Capacidad de batería: 6600 mAh.\n- Carga cableada: 33 W.'},
  {domain:'PRODUCT',productId:'P-22',section:'RESISTENCIA',source:'TEST',text:'Producto: Armor 22\n- Certificación IP68: Sí.\n- Certificación IP69K: Sí.\n- MIL-STD-810H: Sí.\n- Resistencia a caídas: 1.5 m.\n- Profundidad IP68: 1.5 m.\n- Tiempo IP68: 30 min.'},
  {domain:'PRODUCT',productId:'P-22',section:'CAMARA',source:'TEST',text:'Producto: Armor 22\n- Cámara principal: 64 MP.\n- Sensor cámara principal: Sony IMX686.\n- Cámara frontal: 8 MP.\n- Visión nocturna: 64 MP.\n- Sensor cámara nocturna: OV64B.\n- Resolución máxima de video: 2K.'},
  {domain:'PRODUCT',productId:'P-22',section:'CONECTIVIDAD',source:'TEST',text:'Producto: Armor 22\n- NFC: Sí.\n- Google Pay: Sí.\n- Versión Bluetooth: 5.2.\n- Wi-Fi 5 GHz: Sí.\n- Estándares Wi-Fi: 802.11 a/b/g/n/ac.'},
  {domain:'PRODUCT',productId:'P-22',section:'PANTALLA',source:'TEST',text:'Producto: Armor 22\n- Tamaño de pantalla: 6.58 pulgadas.\n- Frecuencia de pantalla: 120 Hz.\n- Clase de resolución: FHD+.'},
  {domain:'PRODUCT',productId:'P-22',section:'RENDIMIENTO',source:'TEST',text:'Producto: Armor 22\n- Procesador: MediaTek Helio G96.\n- GPU: Arm Mali-G57 MC2.'},
  {domain:'PRODUCT',productId:'P-X13',section:'BATERIA',source:'TEST',text:'Producto: Armor X13\n- Capacidad de batería: 6320 mAh.\n- Carga cableada: 10 W.'},
  {domain:'PRODUCT',productId:'P-X13',section:'MEMORIA',source:'TEST',text:'Producto: Armor X13\n- RAM física: 6 GB.\n- RAM virtual máxima: 6 GB.\n- Almacenamiento interno: 64 GB.'},
  {domain:'PRODUCT',productId:'P-X13',section:'PANTALLA',source:'TEST',text:'Producto: Armor X13\n- Tamaño de pantalla: 6.52 pulgadas.\n- Clase de resolución: HD+.'},
  {domain:'PRODUCT',productId:'P-X13',section:'RENDIMIENTO',source:'TEST',text:'Producto: Armor X13\n- Procesador: MediaTek Helio G36.\n- GPU: IMG GE8320.'},
  {domain:'PRODUCT',productId:'P-25T',section:'TERMICA',source:'TEST',text:'Producto: Armor 25T Pro\n- Cámara térmica: Sí.\n- Frecuencia térmica: 25 Hz.\n- Resolución térmica horizontal: 160 px.\n- Resolución térmica vertical: 120 px.\n- Temperatura mínima térmica: -10 °C.\n- Temperatura máxima térmica: 550 °C.\n- Aplicación térmica: ThermoVue App.'},
];
function input(overrides:any):any{return{message:'',intent:'CAPABILITY',state:{priorities:[]},rag:rows,verifiedFacts:[],...overrides};}

test('fact kernel extracts labeled bullets including booleans decimals processor and gpu',()=>{const stores=buildProductFactStores(rows);const armor=stores.find(s=>s.product==='Armor 22');assert.ok(armor);assert.equal(armor!.memory.ramPhysical,'8 GB');assert.equal(armor!.battery.capacity,'6600 mAh');assert.equal(armor!.resistance.ip68,true);assert.equal(armor!.resistance.ip69k,true);assert.equal(armor!.resistance.mil810h,true);assert.equal(armor!.connectivity.bluetooth,'5.2');assert.equal(armor!.performance.processor,'MediaTek Helio G96');assert.equal(armor!.performance.gpu,'Arm Mali-G57 MC2');});

test('NFC answer stays inside bundle and gives safe practical implication',()=>{const result=buildFullRagAnswer(input({message:'El Armor 22 tiene NFC?',intent:'CAPABILITY',attribute:'NFC',resolvedProduct:'Armor 22'}));assert.ok(result);assert.match(result!.answer,/NFC/i);assert.match(result!.answer,/Google Pay/i);assert.match(result!.answer,/contactless/i);assert.doesNotMatch(result!.answer,/Bluetooth|Wi.?Fi/i);});

test('resistance answer returns certifications plus drop and immersion evidence',()=>{const result=buildFullRagAnswer(input({message:'El Armor 22 aguanta bien golpes y agua?',intent:'CAPABILITY',attribute:'RESISTENCIA',resolvedProduct:'Armor 22'}));assert.ok(result);assert.match(result!.answer,/IP68/i);assert.match(result!.answer,/IP69K/i);assert.match(result!.answer,/MIL-STD-810H/i);assert.match(result!.answer,/1\.5 m/i);assert.match(result!.answer,/30 min/i);});

test('camera answer groups camera facts naturally without raw labels',()=>{const result=buildFullRagAnswer(input({message:'Qué cámaras tiene el Armor 22?',intent:'CAPABILITY',attribute:'CAMARA',resolvedProduct:'Armor 22'}));assert.ok(result);assert.match(result!.answer,/64 MP/i);assert.match(result!.answer,/Sony IMX686/i);assert.match(result!.answer,/OV64B/i);assert.match(result!.answer,/2K/i);assert.doesNotMatch(result!.answer,/Cámara principal:/i);});

test('night vision answer stays focused on night camera',()=>{const result=buildFullRagAnswer(input({message:'El Armor 22 tiene cámara nocturna?',intent:'CAPABILITY',resolvedProduct:'Armor 22'}));assert.ok(result);assert.match(result!.answer,/64 MP/i);assert.match(result!.answer,/OV64B/i);assert.doesNotMatch(result!.answer,/Sony IMX686|frontal de 8 MP/i);});

test('gaming suitability uses processor gpu RAM display and avoids invented FPS',()=>{const result=buildFullRagAnswer(input({message:'Con el Armor 22 puedo jugar Free Fire?',intent:'EVALUATE_USE',resolvedProduct:'Armor 22',useCase:'gaming'}));assert.ok(result);assert.match(result!.answer,/Helio G96/i);assert.match(result!.answer,/Mali-G57/i);assert.match(result!.answer,/8 GB/i);assert.match(result!.answer,/120 Hz/i);assert.match(result!.answer,/Free Fire/i);assert.match(result!.answer,/benchmark|FPS/i);assert.doesNotMatch(result!.answer,/60 FPS|90 FPS|120 FPS/i);});

test('work suitability includes processor instead of naming processor abstractly',()=>{const result=buildFullRagAnswer(input({message:'Para WhatsApp, correo y varias apps de trabajo, qué tal el Armor X13?',intent:'EVALUATE_USE',resolvedProduct:'Armor X13',useCase:'trabajo'}));assert.ok(result);assert.match(result!.answer,/Helio G36/i);assert.match(result!.answer,/6 GB/i);assert.match(result!.answer,/64 GB/i);});

test('battery comparison computes grounded winner and omits unrelated camera facts',()=>{const result=buildFullRagAnswer(input({message:'Entre el X13 y el Armor 22 cuál tiene mejor batería?',intent:'COMPARE',decision:{attributes:['BATERIA']}}));assert.ok(result);assert.match(result!.answer,/6320/i);assert.match(result!.answer,/6600/i);assert.match(result!.answer,/33/i);assert.match(result!.answer,/Armor 22 tiene más capacidad/i);assert.doesNotMatch(result!.answer,/Sony|64 MP/i);});

test('gaming comparison uses processor RAM and refresh without camera dump',()=>{const result=buildFullRagAnswer(input({message:'Entre el X13 y el Armor 22 cuál conviene más para jugar Free Fire?',intent:'COMPARE',decision:{attributes:['RENDIMIENTO']},useCase:'gaming'}));assert.ok(result);assert.match(result!.answer,/Helio G36/i);assert.match(result!.answer,/Helio G96/i);assert.match(result!.answer,/6 GB/i);assert.match(result!.answer,/8 GB/i);assert.match(result!.answer,/120 Hz/i);assert.doesNotMatch(result!.answer,/64 MP|Sony/i);});

test('broad comparison ignores planner invented attributes and compares general useful facts',()=>{const result=buildFullRagAnswer(input({message:'Cuál es la diferencia entre el X13 y el Armor 22?',intent:'COMPARE',decision:{attributes:['DURABILITY','PERFORMANCE','BATTERY','CAMERA']}}));assert.ok(result);assert.match(result!.answer,/6320/i);assert.match(result!.answer,/6600/i);assert.match(result!.answer,/6 GB/i);assert.match(result!.answer,/8 GB/i);});

test('thermal recommendation prefers product that actually has thermal capability',()=>{const result=buildFullRagAnswer(input({message:'Necesito un celular con cámara térmica, cuál tienen?',intent:'RECOMMEND',recommendedProduct:'Armor 22',priorities:['termica']}));assert.ok(result);assert.match(result!.answer,/Armor 25T Pro/i);assert.match(result!.answer,/25 Hz/i);assert.match(result!.answer,/160×120/i);assert.doesNotMatch(result!.answer,/Armor 22:.*térmica/i);});

test('planner wrapper keeps Google Pay as direct capability',async()=>{const delegate:any={decide:async()=>({decision:{primaryIntent:'EVALUATE_USE',secondaryIntents:[],targetProduct:'Armor 22',mentionedProducts:['Armor 22'],referenceType:null,explicitSwitch:false,selectedProduct:null,comparisonProducts:[],attributes:['CONECTIVIDAD'],customerNeed:'Google Pay',customerProblem:null,priorities:[],objection:null,commercialStage:null,spinContribution:null,nextBestAction:'ANSWER_ONLY',needsSql:false,needsProductRag:true,needsInstitutionalRag:false,confidence:.9},model:'fake',usage:{inputTokens:0,outputTokens:0,totalTokens:0,cachedInputTokens:0},durationMs:0}),write:async()=>{throw new Error('unused')}};const provider=new FullRagLlmProvider(delegate);const result=await provider.decide({message:'¿El Armor 22 sirve para Google Pay?',state:{} as any});assert.equal(result.decision.primaryIntent,'CAPABILITY');});

test('planner wrapper clears invented criteria from broad comparison',async()=>{const delegate:any={decide:async()=>({decision:{primaryIntent:'COMPARE',secondaryIntents:[],targetProduct:null,mentionedProducts:['Armor X13','Armor 22'],referenceType:null,explicitSwitch:false,selectedProduct:null,comparisonProducts:['Armor X13','Armor 22'],attributes:['DURABILITY','PERFORMANCE','BATTERY'],customerNeed:null,customerProblem:null,priorities:[],objection:null,commercialStage:null,spinContribution:null,nextBestAction:'ANSWER_ONLY',needsSql:false,needsProductRag:true,needsInstitutionalRag:false,confidence:.9},model:'fake',usage:{inputTokens:0,outputTokens:0,totalTokens:0,cachedInputTokens:0},durationMs:0}),write:async()=>{throw new Error('unused')}};const provider=new FullRagLlmProvider(delegate);const result=await provider.decide({message:'Cuál es la diferencia entre el X13 y el Armor 22?',state:{} as any});assert.deepEqual(result.decision.attributes,[]);});

test('real pantalla label Frecuencia de pantalla is parsed as refresh rate',()=>{const stores=buildProductFactStores(rows);const armor=stores.find(s=>s.product==='Armor 22');assert.equal(armor?.display.refresh,'120 Hz');});

test('product overview is compact and ordered as chat bullets',()=>{const result=buildFullRagAnswer(input({message:'Hola, me pasas info del Armor 22?',intent:'PRODUCT_INFO',resolvedProduct:'Armor 22'}));assert.ok(result);assert.match(result!.answer,/^Armor 22:/);assert.match(result!.answer,/\n- /);assert.ok(result!.answer.length<430,`overview too long: ${result!.answer.length}`);});

test('general comparison is concise and highlights differences instead of dumping both fichas',()=>{const result=buildFullRagAnswer(input({message:'Cuál es la diferencia entre el X13 y el Armor 22?',intent:'COMPARE',decision:{attributes:[]}}));assert.ok(result);assert.match(result!.answer,/Armor X13/i);assert.match(result!.answer,/Armor 22/i);assert.match(result!.answer,/\n- /);assert.ok(result!.answer.length<620,`comparison too long: ${result!.answer.length}`);assert.doesNotMatch(result!.answer,/sensor Samsung|sensor Sony/i);});
