import type { Intent } from '../conversation/intent/IntentResolver.ts';

export type CustomerType = 'PERSONAL' | 'BUSINESS';
export type ConversationState = {
  sessionId?: string;
  contextVersion?: number;
  activeProduct?: string|null;
  activeProductId?: string|null;
  activeProductCode?: string|null;
  salientProduct?: string|null;
  selectedProduct?: string|null;
  recommendedProduct?: string|null;
  comparisonProducts?: string[];
  queryTarget?: string|null;
  explicitSwitch?: boolean;
  budget?: number|null;
  lastIntent?: Intent|string|null;
  secondaryIntents?: string[];
  lastRoute?: string|null;
  lastSqlTools?: string[];
  requiresSql?: boolean;
  requiresRag?: boolean;
  spinFacts?: string[];
  lastSpinContribution?: string|null;
  lastNba?: string|null;
  customerType?: CustomerType|null;
  sector?: string|null;
  useCase?: string|null;
  problem?: string|null;
  priorities?: string[];
  quantity?: number|null;
  invoiceRequired?: boolean|null;
  objection?: string|null;
  purchaseSignal?: boolean;
  commercialStage?: string|null;
  commercialStrategy?: string|null;
  handoffActive?: boolean;
  blockAutomaticReply?: boolean;
  handoffReason?: string|null;
  lastResolvedProductId?: string|null;
  lastResolvedProductCode?: string|null;
  lastProductResolutionConfidence?: number|null;
  lastProductResolutionOrigin?: string|null;
  lastUserMessage?: string|null;
  lastAssistantMessage?: string|null;
  turnCount?: number;
  updatedAt?: string;
};

export type ProductQuote = {
  product: string;
  shortName?: string|null;
  productCode?: string|null;
  productRagId?: string|null;
  internalId?: number|null;
  sku?: string|null;
  partNumber?: string|null;
  ean?: string|null;
  price: number|null;
  stock: number|null;
  currency: string;
  categoryCode?: string|null;
  category?: string|null;
  subcategoryCode?: string|null;
  subcategory?: string|null;
  warrantyMonths?: number|null;
  commercialState?: string|null;
  matchScore?: number|null;
  matchPosition?: number|null;
  matchCount?: number|null;
  requiresClarification?: boolean|null;
  resultType?: string|null;
  source: 'FAKE_TEST_DATA'|'SQL_BRIDGE'|'SQL_SERVER';
};

export type CatalogResolution = Record<string, unknown>;
export type CategoryOption = { code:string; name:string; description?:string|null };
export type SubcategoryOption = { code:string; name:string; categoryCode?:string|null; category?:string|null; description?:string|null };
export type OrderLookup = Record<string, unknown>;
export type ProductImage = { url:string; type?:string|null; source:'FAKE_TEST_DATA'|'SQL_BRIDGE'|'SQL_SERVER' };
export type RagEvidence = { text:string; source:string; score?:number; productId?:string|null; section?:string|null; domain?:'PRODUCT'|'INSTITUTIONAL' };
export type VerifiedFact = {
  domain:'SQL'|'PRODUCT_RAG'|'INSTITUTIONAL_RAG';
  key:string;
  value:string;
  productId?:string|null;
  source:string;
};
export type ChatInput = { sessionId:string; message:string; messageId?:string };
export type LlmDebug = { model:string; inputTokens:number|null; outputTokens:number|null; totalTokens:number|null; cachedInputTokens:number|null; durationMs:number };
export type DeliveryDebug = { delivered:boolean; error?:string };

export type ChatTurnResult = {
  sessionId:string;
  answer:string;
  state:ConversationState;
  debug:{
    intent:string;
    secondaryIntents?:string[];
    route?:string;
    sqlTools?:string[];
    queryTarget:string|null;
    explicitSwitch:boolean;
    budget:number|null;
    priceObjection:boolean;
    erp?:ProductQuote|null;
    images?:ProductImage[];
    ragSources?:string[];
    planner?:LlmDebug;
    plannerFallback?:DeliveryDebug;
    llm?:LlmDebug;
    writerFallback?:DeliveryDebug;
    totalDurationMs?:number;
    telemetry?:DeliveryDebug;
    automation?:DeliveryDebug;
  };
};

export type AutomationEvent = { type:'conversation.turn.completed'|'handoff.requested'|'purchase.intent'|'notification.requested'; occurredAt:string; sessionId:string; payload:Record<string,unknown> };
