import { fold } from '../../shared/text.ts';

export type Budget = { kind: 'CAP' | 'RANGE'; min: number | null; max: number; source: 'CURRENT_TURN' | 'MEMORY' };
export type BudgetClassification = { budget: Budget | null; effectiveBudget: Budget | null; budgetConstraint: boolean; budgetQuery: boolean; priceObjection: boolean; preferredIntent: 'RECOMMEND_WITHIN_BUDGET' | 'HANDLE_PRICE_OBJECTION' | 'BUDGET_CONSTRAINT' | null; spinResidual: string; };
function parseMoney(raw: string): number | null { let s = raw.replace(/[^0-9.,]/g, ''); if (!s) return null; if (s.includes(',') && s.includes('.')) { const lastComma=s.lastIndexOf(','); const lastDot=s.lastIndexOf('.'); const dec=Math.max(lastComma,lastDot); const frac=s.length-dec-1; if(frac===2)return Number(s.slice(0,dec).replace(/[.,]/g,'')+'.'+s.slice(dec+1)); return Number(s.replace(/[.,]/g,'')); } const thousand=s.match(/^([0-9]{1,3})[,.]([0-9]{3})$/); if(thousand)return Number(thousand[1]+thousand[2]); if((s.match(/[,.]/g)??[]).length>1)return Number(s.replace(/[.,]/g,'')); if(/[,.]/.test(s)){ const [a,b]=s.split(/[,.]/); if(b?.length===3)return Number(a+b); if(b?.length===2)return Number(a+'.'+b); } const n=Number(s); return Number.isFinite(n)?n:null; }
function detectBudget(message:string):Budget|null{const t=fold(message);const money='(?:s\\s*\\/\\s*)?([0-9][0-9.,]*)';const range=t.match(new RegExp('(?:entre|de)\\s*'+money+'\\s*(?:y|a|-)\\s*'+money,'i'));if(range){const a=parseMoney(range[1]),b=parseMoney(range[2]);if(a!=null&&b!=null)return{kind:'RANGE',min:Math.min(a,b),max:Math.max(a,b),source:'CURRENT_TURN'};}const leading='(?:presupuesto(?:\\s+maximo)?|tengo\\s+maximo|mi\\s+maximo|(?:mi\\s+)?tope|maximo|hasta|no\\s+mas\\s+de|menos\\s+de|por\\s+menos\\s+de|puedo\\s+gastar(?:\\s+hasta)?|podria\\s+gastar(?:\\s+hasta)?|puedo\\s+pagar(?:\\s+hasta)?)';const patterns=[new RegExp(leading+'(?:\\s+(?:de|es))?\\s*'+money,'i'),new RegExp(money+'\\s*(?:soles?|pen)?\\s*(?:es|seria|seria mi)?\\s*(?:mi\\s+)?(?:presupuesto|maximo|max|tope)','i')];for(const rx of patterns){const match=t.match(rx);if(!match)continue;const nums=match.slice(1).map(parseMoney).filter((v):v is number=>v!=null);if(nums.length)return{kind:'CAP',min:null,max:nums.at(-1)!,source:'CURRENT_TURN'};}if(/\bpresupuesto\b/.test(t)){const match=t.match(new RegExp(money,'i'));if(match){const n=parseMoney(match[1]);if(n!=null)return{kind:'CAP',min:null,max:n,source:'CURRENT_TURN'};}}return null;}
function detectPriceObjection(message:string):boolean{const t=fold(message);return /\b(esta|es|me parece)\s+(?:muy\s+)?car[oa]\b|\bcar[oa]\b|\bdemasiado(?:\s+car[oa])?\b|\b(?:se\s+)?sale\s+de\s+mi\s+presupuesto\b|\bfuera\s+de\s+mi\s+presupuesto\b|\bno\s+quiero\s+gastar\s+tanto\b|\bno\s+puedo\s+pagar\b|\blo\s+vi\s+mas\s+barato\b/.test(t);}
function detectBudgetQuery(message:string):boolean{const t=fold(message);return /\b(?:cual|cuales|que)\b[^?.!]{0,50}\b(?:entra|entran|cabe|caben|queda|quedan)\b[^?.!]{0,30}\b(?:mi\s+)?presupuesto\b|\b(?:dentro|por debajo)\s+de\s+(?:mi\s+)?presupuesto\b|\b(?:hay|tienen|tienes)\b[^?.!]{0,35}\b(?:algo|opcion|equipo|celular|modelo)\b[^?.!]{0,35}\b(?:menos\s+de|hasta|maximo|tope)\b/.test(t);}
function stripBudgetClause(text:string):string{let t=fold(text);t=t.replace(/(?:y\s+)?(?:busco\s+algo\s+)?(?:entre|de)\s*(?:s\s*\/\s*)?[0-9][0-9.,]*\s*(?:y|a|-)\s*(?:s\s*\/\s*)?[0-9][0-9.,]*/g,' ');t=t.replace(/(?:y\s+)?(?:tengo\s+)?(?:un\s+)?presupuesto(?:\s+maximo)?(?:\s+(?:de|es))?\s*(?:s\s*\/\s*)?[0-9][0-9.,]*/g,' ');t=t.replace(/(?:y\s+)?(?:tengo\s+)?maximo(?:\s+(?:de|es))?\s*(?:s\s*\/\s*)?[0-9][0-9.,]*/g,' ');t=t.replace(/(?:y\s+)?(?:podria|puedo)\s+(?:gastar|pagar)(?:\s+hasta)?\s*(?:s\s*\/\s*)?[0-9][0-9.,]*/g,' ');t=t.replace(/(?:y\s+)?(?:(?:mi\s+)?tope|maximo|hasta|no\s+mas\s+de|(?:por\s+)?menos\s+de)(?:\s+(?:de|es))?\s*(?:s\s*\/\s*)?[0-9][0-9.,]*/g,' ');t=t.replace(/(?:s\s*\/\s*)?[0-9][0-9.,]*\s*(?:soles?|pen)?\s*(?:maximo|max|tope)\b/g,' ');return t.replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
export function classifyBudgetTurn(message:string,options:{prevBudget?:number|null}={}):BudgetClassification{const budget=detectBudget(message);const budgetQuery=detectBudgetQuery(message);const priceObjection=detectPriceObjection(message);const effectiveBudget=budget??(options.prevBudget!=null?{kind:'CAP',min:null,max:Number(options.prevBudget),source:'MEMORY'}:null);const spinResidual=budget?stripBudgetClause(message):fold(message);return{budget,effectiveBudget,budgetConstraint:Boolean(budget),budgetQuery,priceObjection,preferredIntent:budgetQuery&&effectiveBudget?'RECOMMEND_WITHIN_BUDGET':priceObjection?'HANDLE_PRICE_OBJECTION':budget?'BUDGET_CONSTRAINT':null,spinResidual};}
